# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./pgdb:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    image: shop
    container_name: shop
    build: .
    restart: "always"
    ports:
      - "8002:8000"
    env_file:
      - .env
    links:
      - db
    depends_on:
      - "db"
      - "redis"

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379