# Generated by Django 5.1.5 on 2025-02-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='First name'),
        ),
    ]
