# Generated by Django 5.1.5 on 2025-03-17 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_contact_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='name',
        ),
    ]
