# Generated by Django 5.1.5 on 2025-04-14 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_basket_items_basketitem_basket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basketitem',
            options={'ordering': ('-created_at',)},
        ),
    ]
